### ISSUE TITLE
Doesn't jump to next/previous highlights

### ISSUE THREAD

**Issue by cihadturhan** [minman/browse-word-at-caret#22]
<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd> and <kbd>Down</kbd> buttons doesn't do expected actions.

I already removed next/previous occurence shortcuts.
![image](https://cloud.githubusercontent.com/assets/3739536/9439577/f2a2ec90-4a70-11e5-92a7-a8d3806102d2.png)

Thanks

**Comment by minman** [comment]
And the BrowseWordAtCaret Action shortcuts are set?
![screen](https://cloud.githubusercontent.com/assets/1247254/9441299/88b19caa-4a75-11e5-89d8-5412469d0d27.png)

**Comment by minman** [comment]
please try also the 'Find Actions by Shortcut' (the small icon at right of filter entry), just to be sure there is no conflict with another plugin/action with the same shortcut

**Comment by cihadturhan** [comment]
Same as above:

![image](https://cloud.githubusercontent.com/assets/3739536/9441434/b84d93de-4a7e-11e5-8d75-09c0cc6befee.png)

I'm using PhpStorm 9.0

**Comment by cihadturhan** [comment]
> please try also the 'Find Actions by Shortcut' (the small icon at right of filter entry), just to be sure there is no conflict with another plugin/action with the same shortcut

Uh, I think there is a problem. I couldn't type ctrl+alt+up or down there. I think it's blocked by another application. I'll look for it. Since it's not related to plugin, I'm closing it. 

Thank you
