### ISSUE TITLE
finding next instance of a part of a word

### ISSUE THREAD

**Issue by skeets23** [minman/browse-word-at-caret#24]
I just started using the plugin today, and it works great! There is just one thing that doesn't work as it would be expected. When I select only half a word, and hit Ctrl+Alt+arrow, I would expect it to find the next instance of that word fraction, not the whole word. This is especially true when I am searching for the next instance of a word that is in a camel-case variable, etc.

**Comment by minman** [comment]
Ok, I can improve this. But it will only work with camel case words. So if you have 'myFooBar' and you perform browse with 'myFoo' it will find 'myFooBar', 'myFooBaz', 'myFoo' but not 'myFoolish'.

**Comment by minman** [comment]
New Option `Settings|Editor|Appearance` -> `Support "CamelHumps" when selecting`
