### ISSUE TITLE
Unable to install - can't find it

### ISSUE THREAD

**Issue by TCB13** [minman/browse-word-at-caret#26]
Hello,

I was looking for this great plugin however I can't get it using PHPStrom because it is not available:

![captura de ecra 2017-06-28 as 22 04 33](https://user-images.githubusercontent.com/6315832/27660125-eca1c000-5c4d-11e7-83d9-69876ecf08f8.png)

Thank you.

**Comment by minman** [comment]
have you clicked "Install JetBrians plugin" instead "Browse repositories"?

**Comment by TCB13** [comment]
@minman thanks for the answer, yes I did. As you can see I'm on the plugin installation window:

![captura de ecra 2017-06-28 as 22 11 22](https://user-images.githubusercontent.com/6315832/27660358-cc630cd0-5c4e-11e7-854e-936083b45d8c.png)

**Comment by minman** [comment]
![image](https://user-images.githubusercontent.com/1247254/27660406-566eaad0-5c57-11e7-9f21-540e766c114a.png)

**Comment by TCB13** [comment]
Oh! its working, sorry for the confusion. Many thanks.

**Comment by minman** [comment]
you're welcome.
