### ISSUE TITLE
Not working at all for me :(

### ISSUE THREAD

**Issue by sam-s4s** [minman/browse-word-at-caret#27]
I have a fresh install of WebStorm, and just installed the BrowseWordAtCaret plugin - when pressing Ctrl+Alt+Up/Down, nothing happens...

I even removed the "next / Previous Occurance" controls just in case there was a conflict.

Does this plugin no longer work? :(

WebStorm 2017.2.4

**Comment by minman** [comment]
No, It should work. Can you change shortcut for Browse Next/Previous  word to something else, just to be sure there isn't another conflict?

**Comment by sam-s4s** [comment]
"Another known limitation is: Ctrl+Alt+Up/Down doesn't work under Remote Desktop."
Ah thank you! This will be it! :D
