### ISSUE TITLE
Ignore case & Incremental highlight.

### ISSUE THREAD

**Issue by ss005** [minman/browse-word-at-caret#28]
Thank you for this awesome plugin.
1. Just wondering, is there any option to ignore case while highlighting the occurrences?
2. Can we do incremental highlight as well?

I'm using IDEA 2019.3

**Comment by KyleMit** [comment]
Yeah, I'd love to see this match against any substring even if it doesn't compose a complete symbol


For example, when selecting <code><b>UserAsEmployee</b>Base</code>, it would be nice if it highlighted <code><b>UserAsEmployee</b>Staff</code>


![image](https://user-images.githubusercontent.com/4307307/233173532-e56df52a-b5e1-4799-9903-eac13f11a9ef.png)

**Comment by minman** [comment]
check the option `Settings|Editor|General|Appearance`  -> `Support "CamelHumps" when selecting`
ref #24
