### ISSUE TITLE
Allow the selection to begin and end with non-alphanumeric characters

### ISSUE THREAD

**Issue by somethingSTRANGE** [minman/browse-word-at-caret#29]
I'm using **BrowseWordAtCaret 3.0.4** in Rider 2019.3, so that I can get matching selection behavior that I was used to in Visual Studio (with the Productivity Power Tools extension).

When the selection begins or ends with non-alphanumeric characters, the matches (elsewhere in code) disappear. This prevents me from being able to select entire lines (from the left most column) or to simply end a selection with an operator, semicolon, or other punctuation.

It would be great if the plugin was updated to allow non-alphanumeric characters (including whitespace) to begin and end a selection.

Last year, I started the [Rider Forum: Highlighting matching selected text](https://rider-support.jetbrains.com/hc/en-us/community/posts/360004373959-Highlighting-matching-selected-text?page=1#community_comment_360002066380) thread on the Rider Support forum about the text selection behavior, and I just recently added a comment with an [Animated GIF](https://rider-support.jetbrains.com/hc/user_images/uqvXcgYC7aBTk1Wmi-ekeg.gif) showing the current BrowseWordAtCaret behavior. The original post includes a screenshot of the behavior I'm looking for, which is available in Visual Studio (with the free Productivity Power Tools extension from Microsoft DevLabs).

As an added bonus, it would be ideal if the whitespace at the beginning and end of each line (or maybe all whitespace) was ignored or fudged so that selecting the entire first line with a lot of starting whitespace would also select the lines with different beginning and trailing whitespace ... and the line with more spaces between the `=` and `4` ... and lines that include `\t` tabs vs spaces. 

```    
            var x = 4;

        var x = 4;

        var x =      4;
```

Thanks!

**Comment by mdonatas** [comment]
I'll go one further. Allow the selection to being/end anywhere. If one selects a single character anywhere that should be good enough for this plugin to highlight its occurrences.

**Comment by minman** [comment]
browse-word-at-caret is strictly word based, to quickly jump from one occurrence to another. there is an option to support camel humps, but still word based. So this is probably not the plugin you are looking for. For any other find I suggest to use build in search.
