### ISSUE TITLE
Highlight on right-side panel and codeglance

### ISSUE THREAD

**Issue by vtushevskiy** [minman/browse-word-at-caret#31]
It does not highlight any results on right-side panel (where we see yellow warnings stripes, for example). And it does not show highlight results on CodeGlance plugin panel

**Comment by minman** [comment]
please check your configuration

![image](https://user-images.githubusercontent.com/1247254/127552663-a267e0d6-2e2b-424a-849b-fd61e1b04312.png)

**Comment by vtushevskiy** [comment]
thanks! it works! I don't know how could I miss it. Nice plugin!

**Comment by minman** [comment]
thank you 👍
