### ISSUE TITLE
Highlight Word at Caret not working

### ISSUE THREAD

**Issue by RoEngel** [minman/browse-word-at-caret#34]
The word at the caret isn't highlighted/selected.

Expected behavior:
When moving the cart to the next word, the previous and current selected word should be selected and when typing, what's typed should be applied everywhere the word was present and selected. 

Actual behavior:
When moving the cart to the next word, the caret just jumps to the next occurrence, and when typing the letters are just applied to where the caret is (normal behavior)

Attempted solutions:
1. Selected/Checked  --> View|Highlight Word at Caret. Didn't change the behavior.
2. Selected all the checkboxes at --> Settings|Editor|General|Appearance. Didn't solve the issue.

PS:
I don't think it changes anything but I did assign new shortcuts to the plugin since the original ones conflicted with my current ones.

Plugin version: 3.0.5
Android Studio version:

![image](https://user-images.githubusercontent.com/60978745/147768137-b0ffb016-71cb-4245-8710-3df66893d419.png)

Thanks for your time and effort.

**Comment by minman** [comment]
I just noticed that changing the "View|Highlight word on caret" option no longer direclty affects the open editors. You can workaround this by closing the and reopening the editor/file after you changed that option.

The plugin is intended for navigation only, not for inline editing of all occurrences. For that, the built-in rename (Shift F6) does the job very well.

**Comment by RoEngel** [comment]
Regardless of the editing option, it's supposed to highlight/select all occurrences, no?
If that's it's correct, then it's not doing that.
BTW, I've been using this extension for a long time (great extension) and I f I remember correctly, when selecting all occurrences of a text, it would add multiple carets and enable editing in multiple locations.
I think it was this extension that did that.

**Comment by minman** [comment]
Yes, it does highlight all occurrences. Can you please check your color config? 
![image](https://user-images.githubusercontent.com/1247254/147833653-9126716b-442a-4cf8-9d11-802441b43cfd.png)
