### ISSUE TITLE
Setting to keep highlight word at caret turned On when you open a new file

### ISSUE THREAD

**Issue by hammy021418** [minman/browse-word-at-caret#35]
I would like to know if there is a way to do always on. Currently I have to trigger it for each file I open and if I close I file I have to reenable it each time I open that file.

**Comment by minman** [comment]
You can define the initial settings for each new editor here:
Settings -> Editor -> General -> Appearance ->> Browse Word at Caret

**Comment by hammy021418** [comment]
O man thankyou for that response yep I see it and turned it on.
